language: node_js
sudo: false
node_js:
  - 8

cache:
  directories:
    - node_modules

script:
  - yarn build

deploy:
  skip_cleanup: true
  provider: npm
  email: olegman.ru@gmail.com
  api_key: $NPM_API_KEY
  on:
    tags: true
    repo: router-async/react-router-async